// <auto-generated />
using System;
using Data.DbContextfile;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531145937_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Entities.Alinacaklar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BorcMiktari")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorcunVerildiğiTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("soyisim")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alinacaklars");
                });

            modelBuilder.Entity("Entities.AlinmisAlinacaklar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlinacaklarId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("OdenenMiktar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToplamBorc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AlinmisAlinacaklars");
                });

            modelBuilder.Entity("Entities.Verilecekler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BorcMiktari")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorcunVerildiğiTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("isim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("soyisim")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Verileceklers");
                });

            modelBuilder.Entity("Entities.VerilmisVerilecekler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OdemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("OdenenMiktar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToplamVerilecek")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VerileceklerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VerilmisVerileceklers");
                });
#pragma warning restore 612, 618
        }
    }
}
